apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: dGVzdGluZzEyMw==   # Base64-encoded "secure_pass"
  MYSQL_DATABASE: bXlkYg==                # Base64-encoded "mydb"
