CREATE DATABASE IF NOT EXISTS mydb CHARSET utf8 COLLATE utf8_unicode_ci;

USE mydb;

CREATE TABLE IF NOT EXISTS healthcheck (
    id INT PRIMARY KEY AUTO_INCREMENT,
    status VARCHAR(255),
    checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);